### ISSUE TITLE
how to capture the total time taken? 

### ISSUE THREAD

**Issue by ravieze** [planetlevel/jot#2]
hi,

we want to capture the total time taken for a given method *.controllers.*  Essentially we want to log the server side timings of the api. 

The 2nd question is, can i instrument log4j and somehow print the corellation id? assume the corellation id is part of the http request that is coming in

the 3rd question is, the report output can i configure to put in such a way that grafana can print connected nodes ?

**Comment by planetlevel** [comment]
1. I didn't build timers into JOT, but it's definitely worth considering.  Would be a nice enhancement and pretty easy to do I think.

2. You should be able to get anything from the HTTP request by instrumenting the service() method...  the first parameter is the HTTPServletRequest.   So your capture would look something like:

captures:
  "#P0.getParameter(\"id\")"

3. Check out https://github.com/planetlevel/jot/blob/master/src/main/java/org/openolly/reporting/RouteGraph.java.   I prototyped some stuff around generating graphviz diagrams for visualizing what happens during a route.  If you create something cool, please consider contributing it back.  Some examples below....

![el](https://user-images.githubusercontent.com/2704076/161395683-7974db3f-ed2c-4471-b464-03037491c821.png)
![tomcat](https://user-images.githubusercontent.com/2704076/161395779-16b3fc74-619a-437a-9565-e755e7688cda.png)

**Comment by planetlevel** [comment]
Closing
