### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by ravieze** [planetlevel/jot#3]
hi,

Seeing performance issues when running with JOT library. 

1. Created Helloworld program. Total time taken to execute the program: 345250 nano seconds or 0.3 milli seconds
2. Ran the same Helloworld program with JOT intrumentation. Now the total time taken is: 30822000 or 30milli second. 
3. Now i ran the same helloworld program in for loop for 10 times the timings vary from: 42844792 nano sec --> 514166 nano sec (42ms -->  0.5ms ; which is still significant performance issue
4. The same exercise with out JOT ranges from: 17208 ns to 1750 ns (0.02 ms --> 0.002 ms )

This seems to be a huge performance issue. Any thoughts? 

I see that most of the time is being spent in `Sensors.enterMethodScope` and `Sensors.LeaveMethodscope` ofthe JOT library. 

Helloworld program:
```
package com;

public class Helloworld {
    static long start = System.nanoTime();
    public static void main(String... s){
        System.out.println("**** hello world ** ");
        for (int i=0;i<10; i++) {
            start = System.nanoTime();
            new Helloworld().hi(i);
        }
    }

    public void hi(int i){
        System.out.println("hi , i:: "+i+" time in nanos: " + (System.nanoTime()-start));
    }
}
``` 

jot file
```
---
# Java Observability Toolkit (JOT)
# https://openo11y.org

sensors:
 - name: "get-ciphers"
   description: "Identifies encryption ciphers"
   methods:
   - "com.Helloworld.hi"
   captures:
   - "#P0"
   debug: true

reports:
 - name: "Encryption Usage"
   type: "list"
   cols: "get-ciphers"
```

From standalone helloworld
```
hi , i:: 0 time in nanos: 17208
hi , i:: 1 time in nanos: 3250
hi , i:: 2 time in nanos: 2291
hi , i:: 3 time in nanos: 2167
hi , i:: 4 time in nanos: 2166
hi , i:: 5 time in nanos: 2042
hi , i:: 6 time in nanos: 1709
hi , i:: 7 time in nanos: 2250
hi , i:: 8 time in nanos: 1750
hi , i:: 9 time in nanos: 1958
```

From standalone helloworld with JOT instrumentation etc
```
 hi , i:: 0 time in nanos: 42844792
   35  Apr 04, 2022 11:18:06 AM org.openolly.Sensor leaveMethodScope
   36  INFO: [JOT get-ciphers] METHOD SCOPE [0] - 1 >> get-ciphers 0 time-nanos:42818583
   ..
  124    hashCode()
  125  [SENSOR] Defaulting to toString() - {class java.lang.Integer:1}
  126: hi , i:: 1 time in nanos: 1660542
  127  [SENSOR] Defaulting to toString() - {class java.lang.Integer:2}
  128: hi , i:: 2 time in nanos: 1521750
  129  [SENSOR] Defaulting to toString() - {class java.lang.Integer:3}
  130: hi , i:: 3 time in nanos: 1024750
  131  [SENSOR] Defaulting to toString() - {class java.lang.Integer:4}
  132: hi , i:: 4 time in nanos: 450084
  133  [SENSOR] Defaulting to toString() - {class java.lang.Integer:5}
  134: hi , i:: 5 time in nanos: 499333
  135  [SENSOR] Defaulting to toString() - {class java.lang.Integer:6}
  136: hi , i:: 6 time in nanos: 2153333
  137    registerNatives()
  138    notify()
  ...
  282  INFO: [JOT get-ciphers] METHOD SCOPE [0] - 1 >> get-ciphers 0 time-nanos:522875
  283  [SENSOR] Defaulting to toString() - {class java.lang.Integer:7}
  284: hi , i:: 7 time in nanos: 840917
  285  [SENSOR] Defaulting to toString() - {class java.lang.Integer:8}
  286: hi , i:: 8 time in nanos: 1561125
  287  [SENSOR] Defaulting to toString() - {class java.lang.Integer:9}
  288: hi , i:: 9 time in nanos: 514166
```

**Comment by ravieze** [comment]
If i disable debugging , i see `0.1 milli second` as additional time added to the original method. But the question that remains is, if the bytecode is being manipulated why should the time increase for all the api calls? With debug disabled below are the stats

with JOT instrumentation (nano seconds)
```
hi , i:: 0 time in nanos:22294542
hi , i:: 1 time in nanos:515791
hi , i:: 2 time in nanos:28375
hi , i:: 3 time in nanos:23709
hi , i:: 4 time in nanos:19541
hi , i:: 5 time in nanos:16250
hi , i:: 6 time in nanos:18500
hi , i:: 7 time in nanos:16333
hi , i:: 8 time in nanos:16000
hi , i:: 9 time in nanos:15958
hi , i:: 10 time in nanos:22500
```

Without JOT instrumentation
```
hi , i:: 0 time in nanos:13959
hi , i:: 1 time in nanos:2917
hi , i:: 2 time in nanos:2125
hi , i:: 3 time in nanos:1875
hi , i:: 4 time in nanos:1792
hi , i:: 5 time in nanos:1834
hi , i:: 6 time in nanos:1667
hi , i:: 7 time in nanos:2125
hi , i:: 8 time in nanos:1792
hi , i:: 9 time in nanos:2042
hi , i:: 10 time in nanos:2791
```

**Comment by planetlevel** [comment]
Some performance impact is expected because JOT is doing stuff.  Looks like most of the impact Is due to ‘debug’ being enabled.  I’ll keep this issue open because maybe We can optimize scope usage. 

JOT is primarily to help you understand more complex software in dev/test environment where performance isn’t critical.  I might not use it during my perf test. 

Your test isn’t very realistic (and doesn’t warm up the JIT or other best practices).  All the code does is call the one function you instrumented.  So the code JOT inserts is a significant percentage of the overall code in the app.  Try it on a decent sized web application and see the impact of JOT is really insignificant.

**Comment by ravieze** [comment]
hey! i want to use this for realtime metrics in production. While i like the concept of instrumenting the bytecode --nothing can be more optimized than this, i dont like the idea that we cant use it in perf test. My intent here is to use this in prod and generate observability graphs via grafana 

Can you tell why u worry if we use this in real prod usecase/ in perf test?

btw, can u add a prop file to control logging. nothing gets printed with `.fine()` in logger

**Comment by planetlevel** [comment]
Sure - use it in your performance test.  JOT will have a tiny performance impact.  Closing.
